### ISSUE TITLE
Doctrine Crud generation of many entities at once

### ISSUE THREAD

**Issue by NinjDS** [sensiolabs/SensioGeneratorBundle#168]
Would be nice to have the `generate:doctrine:crud` command to allow these two syntax:

    --bundle=AcmeBlogBundle
    --entities="AcmeBlogBundle:Post/post,AcmeBlogBundle:Author/author"

The former one would generate CRUD for every entity in the bundle. The question is: what to do with "route" switch?
The latter allows a list to be given specifying entities and their routes.

This idea needs to be enhanced. I think it can get really useful when you often modify crud skeleton and needs to rebuild all cruds.

**Comment by javiereguiluz** [comment]
Thanks for proposing this feature. Although it would be nice to have it, I'm closing it as "won't fix". The reason is that we're refocusing the bundle to its core features and this proposal won't be used that much.

If you regenerate lots of entities continuosly, the best alternative would be to create a quick-and-dirty shell script to execute all generation commands in a row. Thanks for understanding it.

**Comment by NinjDS** [comment]
Well, if you say it's not that useful, what can i tell? When you're using custom skeletons, you definitively find that useful. Consider a project with 10s of bundles and 100s of entities and you'll see what i mean :)

"Quick-and-dirty" isn't my way to code, and having a script which will loop through given entities to call `generate:doctrine:crud` is exactly as complex as coding this function into the generator i guess.

I'll just fork it when i'll be using this bundle again. Thank you for the good work anyway :)
