### ISSUE TITLE
[CRUD] Checkboxes for boolean fields are not the right thing

### ISSUE THREAD

**Issue by NinjDS** [sensiolabs/SensioGeneratorBundle#170]
A boolean field can be set to TRUE or FALSE, but also be NULL, which means "this field contains no information". NULL !== FALSE

However, **the CRUD generator cannot handle FALSE boolean**, because it uses checkboxes. For a non-nullable boolean field, a checkbox checked means obviously TRUE, while a non-checked one means FALSE (not NULL!).

But when you don't tick the checkbox of a non-nullable boolean field, you get an error because you must check it, thus forcing it to be TRUE.

**I suggest using a 3-item dropdown list instead:**

    [          ]
    [   TRUE   ]
    [   FALSE  ]

Currently, a workaround is to make the field nullable, but that is not a correct solution. I have a situation right now in which a boolean to NULL means that i must still ask the user for the data when he finalize his order. I must be able to set this boolean to FALSE.

**Comment by javiereguiluz** [comment]
I think that you are right about the possibility of not setting a boolean value and treating it like `null`. However, given the lack of feedback, my guess is that this behavior is not commonly required and most applications treat booleans as true or false. That's why I'm closing this issue as "won't fix". Thanks for understanding it.
