### ISSUE TITLE
only offer "annotation" config if SensioFrameworkExtraBundle is installed

### ISSUE THREAD

**Issue by lsmith77** [sensiolabs/SensioGeneratorBundle#207]
during the bundle generation command annotation should be left out if SensioFrameworkExtraBundle is not installed

**Comment by javiereguiluz** [comment]
@lsmith77 thanks for proposing this improvement and sorry for the ultra late response.

I'm closing this issue as "won't fix" because, from the point of view of this bundle, it doesn't matter if SensioFrameworkExtraBundle is enabled or not. The generated code will always include the right annotations. If your application is not ready to load annotations, that's a different issue. The good news is that a newcomer will never disable the SensioFrameworkExtraBundle, so (hopefully) everything will work for them.
