### ISSUE TITLE
Generators doesn't support psr-4

### ISSUE THREAD

**Issue by nkt** [sensiolabs/SensioGeneratorBundle#264]
In my project uses psr-4 autoloading standard. But generates commands doesn't working fine:
```
$ app/console doc:gen:form VendorEventsBundle:Event
                                                                                                                                                         
  [RuntimeException]                                                                                                                                                                
  Can't find base path for "Vendor\EventsBundle\Entity\Event"
(path: "/Users/nkt/Projects/project/src/EventsBundle/Entity",
destination: "/Users/nkt/Projects/project/src/EventsBundle/Entity").    
```

**Comment by Tobion** [comment]
I tried the `generate:controller` and it worked fine. I don't see what the commands could do wrong as this is autoloading and PSR-4 is a superset of PSR-0 (except PEAR classes). So the problem is most likely that you configured your autoloading wrong.
This issue can be closed. If you can provide concrete problems, feel free to reopen.
