### ISSUE TITLE
[DX] Auto create json responses

### ISSUE THREAD

**Issue by DIOHz0r** [sensiolabs/SensioGeneratorBundle#306]
This was open at symfony/symfony repo (https://github.com/symfony/symfony/issues/12001) the idea is to have the fetaure to have a parameter modification to make the crud generator to populate the actions in the controller with json response format and not in the default way.

**Comment by javiereguiluz** [comment]
In your particular case, it's true that adding this option would come in very handy. However, I don't think this is a common enough scenario. That's why I propose to close this issue as *won't fix*.

Moreover, you say that this improvement would prevent you from changing manually all controllers. That's true, but for real applications you probably have to change all controllers generated by this bundle. The purpose of this bundle is to help you bootstrap your bundle/CRUD/entity, etc.  but a lot of work from the developer is expected afterwards to complete the code.
