### ISSUE TITLE
[DX] Generate DependencyInjection

### ISSUE THREAD

**Issue by bitgandtter** [sensiolabs/SensioGeneratorBundle#308]
In many cases/bundles i start developing from a basic bundle and then its presented to me the need to add configuration trough DI. This process its already implemented and used in the main generator command (full bundle structure generator) .

I think it will be helpful if we extract that generator part and create an extra command to generate DI over an existing bundle, and also reuse that code in the current process.

What do you think? If this get a go i can fork the repo and split it, then propose a pull.

**Comment by javiereguiluz** [comment]
Thanks for proposing this feature. Sadly, I'm closing this issue as "won't fix". The reason is that we reently decided to refocus the purpose of the bundle to not complicate it too much.

Right now we can 1) generate a bundle without the DependencyInjection/ dir and afterwards generate it by hand (it's not that hard) or 2) generate the full bundle which already contains the DependencyInjection/ dir. This proposal would be a middle case which we think is no common enough. Thanks for understanding it.
