### ISSUE TITLE
Is it possible to create a new directory via CRUD command?

### ISSUE THREAD

**Issue by piux** [sensiolabs/SensioGeneratorBundle#311]
greetings, i already know how to override the templates from the skeleton folder, but since im using knp paginator bundle, i was wondering if there a way to create a new folder named builder and put some generated code there?

for example:

    crud/
        views/
        config/
        actions/
        Builder/ <-- new directory that will be generated by crude in my bundle

is it possible?

in case that i need to modify the vendors file, can i override them so whenever i update it doesnt delete the changes?

**Comment by javiereguiluz** [comment]
Right now it's not possible to add or generate your own directories. I'm closing this issue as "won't fix" because it's too specific. Our idea is to add a simple but flexible system to customize/override the generated files and directories. There are several proposals to solve this so we just need to pick one and finish it.
