### ISSUE TITLE
Add delete to the index view

### ISSUE THREAD

**Issue by keymaster** [sensiolabs/SensioGeneratorBundle#53]
In addition to the show and edit, please consider adding the delete command to the index view.

**Comment by javiereguiluz** [comment]
It's not a bad idea at all ... but I'm closing it as "won't fix" because its implementation is very cumbersome.

The reason is that `Delete` links are in fact forms that simulate the `DELETE` HTTP method via a special hidden form field. This means that we need to generate lots of different delete forms to enable this feature.
