### ISSUE TITLE
S3.4 no longer supports BlogBundle:Default:index.html.twig?

### ISSUE THREAD

**Issue by ahundiak** [sensiolabs/SensioGeneratorBundle#587]
Not sure if this is a bug or a feature but running generate:bundle under S3.4 and then browsing to the default controller results in a twig template not found message.  Works fine under S3.3

Changing the template path in the controller from 'BlogBundle:Default:index.html.twig' to '@Blog/Default/index.html.twig' fixes the problem.  

Seems strange the S3.4 would make a change like this.  I know we are supposed to use namespaces paths but dropping the Bundle:Dir:Name support in 3.4 seems a bit of a BC break?

In any event, the generate:bundle command bundle command should probably be tweaked to use a namespaced path for templates.

**Comment by fabpot** [comment]
It depends on how you templating layer is configured. The notation is still available, but only if you are using the templating system instead of Twig directly. New projects on 3.4 (with Flex) uses Twig only where such notation is not supported. Enable `templating` in the framework bundle configuration if you want support.
