### ISSUE TITLE
automatic entity creation issue (in CRUD mode)

### ISSUE THREAD

**Issue by eng1neer** [sensiolabs/SensioGeneratorBundle#71]
`php app/console gen:doctrine:crud` says the following:

```
This command helps you generate CRUD controllers and templates.

First, you need to give the entity for which you want to generate a CRUD.
You can give an entity that does not exist yet and the wizard will help
you defining it.
```

I'm issuing the above command with the `AcmeBlogBundle:Post` entity name (`AcmeBlogBundle` does exist, `Post` does not exist, no any other entities in `AcmeBlogBundle`). Generator answers the following

```
[Doctrine\ORM\ORMException]

Unknown Entity namespace alias 'AcmeBlogBundle'.
```

It only allows to proceed with CRUD generation after explicit Post creation (`php app/console gen:doctrine:entity`). If I have defined entities in `AcmeBlogBundle`, error message is different though the issue stays - wizard doesn't let me automatically create entity during crud generation as it claims to:

```
[Doctrine\ORM\Mapping\MappingException]

Class Acme\BlogBundle\Entity\Post is not a valid entity or mapped super class.

Tested on symfony-standard 2.0.0, 2.0.3 and current version from the Symfony repository.
PHP 5.3.5-1ubuntu7.2 with Suhosin-Patch (cli) (built: May 2 2011 23:00:17)
```

**Comment by ishakuta** [comment]
If it still relevant for someone :)
guys, it's because DoctrineBundle DoctrineExtension compile the list of valid aliases based on all registered bundles, that have 'Entity' (or other configured) folder in them.

So in order to use doctrine:generate:crud or generate:doctrine:crud,
you *have to* create just folder Entity in your bundle, and not required to create entity first (as command says - it's true).

**Comment by javiereguiluz** [comment]
I understand your frustration with this feature that doesn't work. However, instead of fixing it, I propose to remove that feature. Therefore, `generate:doctrine:crud` would only generate a CRUD for existing entities and `generate:doctrine:entity` should be used beforehand to generate that entity.

The benefits would be to have less code and to remove the coupling between these two commands.

**Comment by ishakuta** [comment]
@javiereguiluz agree :+1:

**Comment by javiereguiluz** [comment]
This "feature" has been removed in #386.
